image: node:18

before_script:
  - echo 'export LT_USERNAME="jyotiyadav"' >> ~/.bashrc
  - echo 'export LT_ACCESS_KEY="LT_QADsSrkYtrtgR0gOQKfoxZuVqQTm1DXlbHy0Vo9JkOzJwpe"' >> ~/.bashrc
  - npm install
  - npm install -g protractor
  
job:
  script:
    - protractor single.conf.js
