image: node:18

before_script:
  - echo 'export LT_USERNAME=""' >> ~/.bashrc
  - echo 'export LT_ACCESS_KEY=""' >> ~/.bashrc
  - npm install
  - npm install -g protractor
  
job:
  script:
    - protractor single.conf.js
